#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1436650069                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : $4.99 / $11.99 / 3-day Trial               # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Code Python on iOS

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Emma Labb√©

your_link                                 : https://labbe.me

your_city                                 : Renens
email_address                             : support@pyto.app
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : pytoapp
github_username                           : ColdGrub1384
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :
    
  - title                                 : Python locally
    description                           : Run Python 3.10 code locally on your iPad or iPhone.
    fontawesome_icon_name                 : mobile

  - title                                 : Code Editor
    description                           : Edit code with syntax highlighting and code completion.
    fontawesome_icon_name                 : keyboard

  - title                                 : Terminal
    description                           : Run UNIX commands and your scripts
    fontawesome_icon_name                 : terminal

  - title                                 : Included libraries
    description                           : Pyto includes Numpy, Matplotlib, Pandas, Statsmodels, SciPy, SciKit-Learn, SciKit-Image, OpenCV and more libraries!
    fontawesome_icon_name                 : magic

  - title                                 : System integration
    description                           : Pyto includes libraries for scheduling notifications, accessing location, accessing the music library and more.
    fontawesome_icon_name                 : cog
    
  - title                                 : Tracebacks UI
    description                           : Debug exceptions with easily with an UI for that.
    fontawesome_icon_name                 : exclamation-triangle
    
  - title                                 : Projects
    description                           : Build projects with the integrated file browser and setuptools
    fontawesome_icon_name                 : folder

  - title                                 : Shortcuts
    description                           : Run scripts or custom code with Shortcuts.
    fontawesome_icon_name                 : cubes
  
  - title                                 : Home Screen Widgets
    description                           : Create home screen widgets for iOS 14.
    fontawesome_icon_name                 : calendar-alt
  
  - title                                 : PyPI
    description                           : Install pure Python modules from PyPI.
    fontawesome_icon_name                 : box-open



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0
topbar_title_color                        : "#000000"

cover_image                               :                  # Replace with alternative image path or image URL.
cover_overlay_color                       : "#ffffff"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ededed"

link_color                                : "#1d63ea"

app_title_color                           : "#000000"
app_price_color                           : "#000000"
app_description_color                     : "#000000"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"




####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

theme: jekyll-theme-cayman
